name:                cs421-final-project
version:             0.1
license:             NCSA
author:              "Rodrigo Mendoza"
maintainer:          "rm36@illinois.edu"
copyright:           ""

description:         CS421 Final Project

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2
- containers

library:
  source-dirs: src

tests:
  test:
    main:             ProjectTests.hs
    source-dirs:
    - tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit >= 1.5
    - tasty
    - tasty-hunit
    - cs421-final-project
